version: '3.3'
services:    
    rws_project_creator_dev:
        build: node    
        container_name: rws_project_creator_dev
        # restart: always        
        volumes:
            - ../test:/app